sudo: false
language: node_js

node_js:
  - 8

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - yarn run lint
  - yarn run examples:lint
  - yarn test

notifications:
  email:
    on_success: never
    on_failure: never
